### ISSUE TITLE
Add the ability to measure padding between elements 

### ISSUE THREAD

**Issue by adelaidemt** [blinkk/amagaki-plugin-page-builder#26]
Chrome devtools is not very useful to test redlines from the design file. Wondering if this type of feature is possible? 

I know there are some measuring plugins in Sketch and Figma that are helpful so I wonder if something like that can be built on our page builder. 

cc @jeremydw @micjamking

**Comment by jeremydw** [comment]
We'll add https://github.com/stevenlei/spacingjs into the inspector so users can measure redlines/elements in staging

**Comment by jeremydw** [comment]
https://github.com/blinkk/amagaki-plugin-page-builder/commit/5b2e7520542b9040a3ba08544728a1a5c6e55462 adds SpacingJS to the inspector.

Usage:

1. Use `Ctrl+M` to enable the margin inspector
2. Use `Option` to start measuring
3. Move the cursor to another element

Instructions are also provided in the `?` shortcut helper menu
